version: '3.8'

services:
  app:
    image: yourusername/chils-korean-store:latest
    container_name: chils-korean-store-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/chils_korean_store
      - SESSION_SECRET=${SESSION_SECRET}
    depends_on:
      - mongodb
    volumes:
      - ./uploads:/app/uploads
    networks:
      - app-network

  mongodb:
    image: mongo:6.0
    container_name: chils-korean-store-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=chils_korean_store
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: chils-korean-store-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - app
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge
