version: '3.8'

services:
  app:
    build: .
    container_name: chils-korean-store-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=${MONGODB_URI}
      - SESSION_SECRET=${SESSION_SECRET}
    volumes:
      - ./uploads:/app/uploads

  mongodb:
    image: mongo:6.0
    container_name: chils-korean-store-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=chils_korean_store

volumes:
  mongodb_data:
